# Generated by Django 5.0 on 2024-01-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_customr',
            field=models.BooleanField(default=False),
        ),
    ]
